//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRoadSense.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings_it {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings_it() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartRoadSense.Resources.LogStrings.it", typeof(LogStrings_it).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiornamento del database interno.
        /// </summary>
        public static string DatabaseMigrationReset {
            get {
                return ResourceManager.GetString("DatabaseMigrationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nel caricamento dei dati registrati.
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione fallita: {0}.
        /// </summary>
        public static string FileUploadFailure {
            get {
                return ResourceManager.GetString("FileUploadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione completata ({0} blocchi caricati).
        /// </summary>
        public static string FileUploadSummaryPlural {
            get {
                return ResourceManager.GetString("FileUploadSummaryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizzazione completata (1 blocco caricato).
        /// </summary>
        public static string FileUploadSummarySingular {
            get {
                return ResourceManager.GetString("FileUploadSummarySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nella scrittura dei dati registrati.
        /// </summary>
        public static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovi dati registrati.
        /// </summary>
        public static string FileWriteSuccess {
            get {
                return ResourceManager.GetString("FileWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS disabilitato.
        /// </summary>
        public static string GpsDisabled {
            get {
                return ResourceManager.GetString("GpsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS abilitato.
        /// </summary>
        public static string GpsEnabled {
            get {
                return ResourceManager.GetString("GpsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilevato segnale GPS.
        /// </summary>
        public static string GpsFix {
            get {
                return ResourceManager.GetString("GpsFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perso segnale GPS.
        /// </summary>
        public static string GpsFixLost {
            get {
                return ResourceManager.GetString("GpsFixLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di elaborazione interno.
        /// </summary>
        public static string InternalEngineError {
            get {
                return ResourceManager.GetString("InternalEngineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione ignorata in modalità offline.
        /// </summary>
        public static string RecordingOffline {
            get {
                return ResourceManager.GetString("RecordingOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione avviata.
        /// </summary>
        public static string RecordingStarted {
            get {
                return ResourceManager.GetString("RecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione terminata.
        /// </summary>
        public static string RecordingStopped {
            get {
                return ResourceManager.GetString("RecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione sospesa a causa del movimento troppo lento.
        /// </summary>
        public static string RecordingSuspendedSpeed {
            get {
                return ResourceManager.GetString("RecordingSuspendedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione sospesa perché il dispositivo è rimasto immobile per troppo tempo.
        /// </summary>
        public static string RecordingSuspendedStationary {
            get {
                return ResourceManager.GetString("RecordingSuspendedStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartRoadSense v{0} avviato.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrata traccia di {0:0.0} chilometri ({1} punti).
        /// </summary>
        public static string StatsRecorded {
            get {
                return ResourceManager.GetString("StatsRecorded", resourceCulture);
            }
        }
    }
}
