//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartRoadSense.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogStrings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartRoadSense.Resources.LogStrings", typeof(LogStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updating internal database after update.
        /// </summary>
        public static string DatabaseMigrationReset {
            get {
                return ResourceManager.GetString("DatabaseMigrationReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Synchronization failed: {0}.
        /// </summary>
        public static string FileUploadFailure {
            get {
                return ResourceManager.GetString("FileUploadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Synchronization completed ({0} chunks uploaded).
        /// </summary>
        public static string FileUploadSummaryPlural {
            get {
                return ResourceManager.GetString("FileUploadSummaryPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Synchronization completed (1 chunk uploaded).
        /// </summary>
        public static string FileUploadSummarySingular {
            get {
                return ResourceManager.GetString("FileUploadSummarySingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Failed to write data file.
        /// </summary>
        public static string FileWriteError {
            get {
                return ResourceManager.GetString("FileWriteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a New data written to file.
        /// </summary>
        public static string FileWriteSuccess {
            get {
                return ResourceManager.GetString("FileWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS disabled.
        /// </summary>
        public static string GpsDisabled {
            get {
                return ResourceManager.GetString("GpsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS enabled.
        /// </summary>
        public static string GpsEnabled {
            get {
                return ResourceManager.GetString("GpsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS got satellite fix.
        /// </summary>
        public static string GpsFix {
            get {
                return ResourceManager.GetString("GpsFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS fix lost.
        /// </summary>
        public static string GpsFixLost {
            get {
                return ResourceManager.GetString("GpsFixLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Internal computation error.
        /// </summary>
        public static string InternalEngineError {
            get {
                return ResourceManager.GetString("InternalEngineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recording ignored in offline mode.
        /// </summary>
        public static string RecordingOffline {
            get {
                return ResourceManager.GetString("RecordingOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Started recording.
        /// </summary>
        public static string RecordingStarted {
            get {
                return ResourceManager.GetString("RecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stopped recording.
        /// </summary>
        public static string RecordingStopped {
            get {
                return ResourceManager.GetString("RecordingStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recording suspended because user movement was too slow.
        /// </summary>
        public static string RecordingSuspendedSpeed {
            get {
                return ResourceManager.GetString("RecordingSuspendedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Recording suspended because the device remained stationary for too long.
        /// </summary>
        public static string RecordingSuspendedStationary {
            get {
                return ResourceManager.GetString("RecordingSuspendedStationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SmartRoadSense v{0} started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0:0.0} km track recorded ({1} data points).
        /// </summary>
        public static string StatsRecorded {
            get {
                return ResourceManager.GetString("StatsRecorded", resourceCulture);
            }
        }
    }
}
