using System;
using SQLite;

namespace SmartRoadSense.Shared.Database {

    /// <summary>
    /// Represents a record about an uploaded track chunk.
    /// </summary>
#if __ANDROID__
    [global::Android.Runtime.Preserve(AllMembers = true)]
#endif
    public class TrackUploadRecord {

        public TrackUploadRecord() {
        }

        /// <summary>
        /// Gets or sets the synthetic ID used by this local installation.
        /// </summary>
        [PrimaryKey, AutoIncrement]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the chunk's track ID.
        /// Multiple chunks from the same track will share the same ID.
        /// </summary>
        [Indexed, NotNull]
        public Guid TrackId { get; set; }

        /// <summary>
        /// Gets or sets the unique ID generated by the online service.
        /// </summary>
        [Indexed]
        public int UploadedId { get; set; }

        /// <summary>
        /// Gets or sets the secret generated for this uploaded chunk.
        /// </summary>
        [NotNull]
        public byte[] Secret { get; set; }

        /// <summary>
        /// Gets or sets the timestamp of when the upload was completed (UTC).
        /// </summary>
        [NotNull]
        public DateTime UploadedOn { get; set; }

        #region Added in data version 3

        /// <summary>
        /// Gets or sets the amount of data points uploaded.
        /// </summary>
        public int? Count { get; set; }

        #endregion

    }

}

