// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SmartRoadSense.iOS
{
	public partial class IntroductionPageViewController : UIPageViewController
	{
		public IntroductionPageViewController (IntPtr handle) : base (handle)
		{
		}

		private UIPageViewController pageController;

		public int TotalPages
		{
			get { return 7; }
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.pageController =
				new UIPageViewController(UIPageViewControllerTransitionStyle.Scroll,
					UIPageViewControllerNavigationOrientation.Horizontal,
					UIPageViewControllerSpineLocation.None);

			// Initialize the first page

			IntroductionPageDetailViewController firstPageController = UIStoryboard.FromName ("MainStoryboard", null).InstantiateViewController ("IntroductionPageDetailViewController") as IntroductionPageDetailViewController;
			firstPageController.PageIndex = 0;
			firstPageController.IntroVC = this;

			this.pageController.SetViewControllers(new UIViewController[] { firstPageController }, UIPageViewControllerNavigationDirection.Forward, true, s => { });
			this.pageController.DataSource = new PageDataSource(this);
			this.pageController.View.Frame = this.View.Bounds;
			this.View.AddSubview(this.pageController.View);
		}
	}


}
